const fs = require('fs');
if (fs.existsSync('config.env')) require('dotenv').config({ path: './config.env' });

module.exports = {
  "SESSION_ID": process.env.SESSION_ID || "eyJub2lzZUtleSI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiT0ZwU3hxVjJYMWdwZFdjWGg0aVI3Z0Q0YXVuQmJSYlBCaTNFTEZYaG8zND0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiN2k5dm01SjlxcjZ6TjY4cDlZaWFKRWxNb01TNUR6b25CcUl5NE9kU3JBTT0ifX0sInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyIjp7InByaXZhdGUiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJJRWRIeDhlSGJNa0h6a2VHMVpuY0dyTUFpNWJhVWlNUjh6YXY3V0tsVVdNPSJ9LCJwdWJsaWMiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiIxWHVVM0RNdUtGZ1o1WHpEOEFSbjdjRURDbmhOZmE3RkFWeWZVbFk5dWxVPSJ9fSwic2lnbmVkSWRlbnRpdHlLZXkiOnsicHJpdmF0ZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IkdGV0JXNWNTa2pwOG5MOUlUb0ZBVzJUeDlqTW5IUnVqUjlBMXRTcmcvSDA9In0sInB1YmxpYyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IkJyRkpzUnFiZ3F3ZG5hSUl6dC9lNUorMDdBdjkyTGZXTS9zZDRYZEtmVGc9In19LCJzaWduZWRQcmVLZXkiOnsia2V5UGFpciI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiNEw2TG9ZcWR2OGRJNUhuTjFiTXBmWThGYzVnZURFQ0JNK1Iwai9lTEIxVT0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiRHlFc3dOc0pnM0RPMUdmcHgzclVHeW1LUXJzSzBxcmlhMDdJM0NaYXREcz0ifX0sInNpZ25hdHVyZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6ImQ0S0pqenVsUTJDNEl6cUh0TGI1OGFKUjRZZlMwd0tPWUE3WXhTRzlzdDl2cS9ubGhSOFhDZDZZbjduTHM1TFh4anREdFBZcExSbkJsYktJblg2bkF3PT0ifSwia2V5SWQiOjF9LCJyZWdpc3RyYXRpb25JZCI6MTMzLCJhZHZTZWNyZXRLZXkiOiJJR0lEZ3VISDF3OXhwaTExZ0NlcFdBai9JNSswNEl5UkdVUlNtWmlCOUtZPSIsInByb2Nlc3NlZEhpc3RvcnlNZXNzYWdlcyI6W3sia2V5Ijp7InJlbW90ZUppZCI6IjI1NDc0ODM0MzMyOUBzLndoYXRzYXBwLm5ldCIsImZyb21NZSI6dHJ1ZSwiaWQiOiIxRjQxNDA0NUQ4NjBCNkNDMDlCN0I1NkJEQTk0NDc5NSJ9LCJtZXNzYWdlVGltZXN0YW1wIjoxNzUwNjI1MjkxfSx7ImtleSI6eyJyZW1vdGVKaWQiOiIyNTQ3NDgzNDMzMjlAcy53aGF0c2FwcC5uZXQiLCJmcm9tTWUiOnRydWUsImlkIjoiRjFFQjhFRjE4MUM2NEZFQzE5M0RBNTQzRkQwMjM3NzIifSwibWVzc2FnZVRpbWVzdGFtcCI6MTc1MDYyNTI5MX0seyJrZXkiOnsicmVtb3RlSmlkIjoiMjU0NzQ4MzQzMzI5QHMud2hhdHNhcHAubmV0IiwiZnJvbU1lIjp0cnVlLCJpZCI6IjgyM0VBNDhFNzRBMjdCN0ZBN0Q3NDE3M0I0NjcxMzZDIn0sIm1lc3NhZ2VUaW1lc3RhbXAiOjE3NTA2MjUzMjl9XSwibmV4dFByZUtleUlkIjozMSwiZmlyc3RVbnVwbG9hZGVkUHJlS2V5SWQiOjMxLCJhY2NvdW50U3luY0NvdW50ZXIiOjEsImFjY291bnRTZXR0aW5ncyI6eyJ1bmFyY2hpdmVDaGF0cyI6ZmFsc2V9LCJyZWdpc3RlcmVkIjp0cnVlLCJwYWlyaW5nQ29kZSI6IlRXTEpYVjIyIiwibWUiOnsiaWQiOiIyNTQ3NDgzNDMzMjk6MkBzLndoYXRzYXBwLm5ldCIsImxpZCI6IjI1MTcxNTc4NTg3OTU4ODoyQGxpZCIsIm5hbWUiOiJNci5UZWNoIn0sImFjY291bnQiOnsiZGV0YWlscyI6IkNQWHI1Uk1RKzlmaHdnWVlBU0FBS0FBPSIsImFjY291bnRTaWduYXR1cmVLZXkiOiJKU1k1ZjBRa05sdm9kSjdzeXh3bExIWWpCclNIQmhsaWk0NVJXVkZkdnpRPSIsImFjY291bnRTaWduYXR1cmUiOiJIdEd0bllSbEhRekN0V1pCbHd4TUFDYlQ1b3RhVGdvVWE0UDNhL1ZlcHNpTnVDM2s2VWwrRkQ2dm16MkxsK0xiZksyK2pNYk56dWVLaWVPNHVzOFpBdz09IiwiZGV2aWNlU2lnbmF0dXJlIjoid0ZIZGdjbkp2aGVMdHhjNzJrbHVTSWJMQWJ6YnpDQmUwR2hjYWx0dnIyakkwczVyWGl1cjdIcXZlZFpDZ05UcDhvOVZVaDZSamwyekhLWUpLeS9nRGc9PSJ9LCJzaWduYWxJZGVudGl0aWVzIjpbeyJpZGVudGlmaWVyIjp7Im5hbWUiOiIyNTQ3NDgzNDMzMjk6MkBzLndoYXRzYXBwLm5ldCIsImRldmljZUlkIjowfSwiaWRlbnRpZmllcktleSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IkJTVW1PWDlFSkRaYjZIU2U3TXNjSlN4Mkl3YTBod1laWW91T1VWbFJYYjgwIn19XSwicGxhdGZvcm0iOiJhbmRyb2lkIiwicm91dGluZ0luZm8iOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJDQUlJRWc9PSJ9LCJsYXN0QWNjb3VudFN5bmNUaW1lc3RhbXAiOjE3NTA2MjUyODgsImxhc3RQcm9wSGFzaCI6IjJWNzdxVSIsIm15QXBwU3RhdGVLZXlJZCI6IkFBQUFBSWphIn0=",
  "ALIVE_IMG": process.env.ALIVE_IMG || "https://raw.githubusercontent.com/HyHamza/HyHamza/refs/heads/main/Images/logo.jpg",
  "PREFIX": process.env.PREFIX || ".",
  "AUTO_READ_STATUS": process.env.AUTO_READ_STATUS === 'true',
  "MODE": process.env.MODE || "public",
  "OWNER_NUMBER": process.env.OWNER_NUMBER || "923072380380",
  "OWNER_NAME": process.env.OWNER_NAME || "Hamza",
  "ALWAYS_ONLINE": process.env.ALWAYS_ONLINE === 'true',
  "PRESENCE": process.env.PRESENCE || "online",
  "OMDB_API_KEY": process.env.OMDB_API_KEY || "76cb7f39",
  "READ_CMD": process.env.READ_CMD === 'true',
  "AUTO_VOICE": process.env.AUTO_VOICE === 'true',
  "AUTO_STICKER": process.env.AUTO_STICKER === 'true',
  "AUTO_REPLY": process.env.AUTO_REPLY === 'true',
  "AUTO_REACT": process.env.AUTO_REACT === 'true',
  "WELCOME": process.env.WELCOME === 'true',
  "ANTI_BAD": process.env.ANTI_BAD === 'true',
  "ANTI_LINK": process.env.ANTI_LINK === 'true',
  "ANTI_GROUP_LINK": process.env.ANTI_GROUP_LINK === 'true',
  "ANTI_DELETE": process.env.ANTI_DELETE === 'true',
  "ANTI_VIEW_ONCE": process.env.ANTI_VIEW_ONCE === 'true',
  "ANTI_BOT": process.env.ANTI_BOT === 'true',
  "PREMIUM_USERS": process.env.PREMIUM_USERS || "",
  "COUNTRY_BLOCK": process.env.COUNTRY_BLOCK === 'true',
  "COUNTRY_BLOCK_CODE": process.env.COUNTRY_BLOCK_CODE || "972",
  "EMOJI": process.env.EMOJI || "🙄",
  "AUTO_TYPING": process.env.AUTO_TYPING === 'true'
};
